//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpeedKyat.InternationalMobile.Topup.Infrastructure.Persistence.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurrencyDetail
    {
        public CurrencyDetail()
        {
            this.TopupTransactions = new HashSet<TopupTransaction>();
        }
    
        public System.Guid CurrencyDetailId { get; set; }
        public string CountryName { get; set; }
        public string CurrencyType { get; set; }
        public double ExchangeRate { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual ICollection<TopupTransaction> TopupTransactions { get; set; }
    }
}
