//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpeedKyat.InternationalMobile.Topup.Infrastructure.Persistence.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TopupTransaction
    {
        public System.Guid TopupTransactionId { get; set; }
        public System.Guid CustomerId { get; set; }
        public string CountryCode { get; set; }
        public string OperatorName { get; set; }
        public string TopupNumber { get; set; }
        public double Amount { get; set; }
        public double AmountInMMK { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string TopupStatus { get; set; }
        public string ErrorMessage { get; set; }
        public string OkTransactionId { get; set; }
        public string OkTransactionStatus { get; set; }
        public string DestinationNumber { get; set; }
        public Nullable<System.Guid> TopupTransactionReferenceId { get; set; }
        public System.Guid CurrencyDetailId { get; set; }
        public string Reference1 { get; set; }
        public string Reference2 { get; set; }
    
        public virtual CurrencyDetail CurrencyDetail { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
